// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentIO.Data;

#nullable disable

namespace RentIO.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentIO.Models.Apartman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("numeric");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Apartmani");
                });

            modelBuilder.Entity("RentIO.Models.Gost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Gosti");
                });

            modelBuilder.Entity("RentIO.Models.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatumDolaska")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumOdlaska")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GostId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UkupnaCijena")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ApartmanId");

                    b.HasIndex("GostId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("RentIO.Models.RezervacijaUsluga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Kolicina")
                        .HasColumnType("integer");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("integer");

                    b.Property<int>("UslugaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RezervacijaId");

                    b.HasIndex("UslugaId");

                    b.ToTable("RezervacijaUsluge");
                });

            modelBuilder.Entity("RentIO.Models.Usluga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaPoJedinici")
                        .HasColumnType("numeric");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Usluge");
                });

            modelBuilder.Entity("RentIO.Models.Rezervacija", b =>
                {
                    b.HasOne("RentIO.Models.Apartman", "Apartman")
                        .WithMany("Rezervacije")
                        .HasForeignKey("ApartmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentIO.Models.Gost", "Gost")
                        .WithMany("Rezervacije")
                        .HasForeignKey("GostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartman");

                    b.Navigation("Gost");
                });

            modelBuilder.Entity("RentIO.Models.RezervacijaUsluga", b =>
                {
                    b.HasOne("RentIO.Models.Rezervacija", "Rezervacija")
                        .WithMany("RezervacijaUsluge")
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentIO.Models.Usluga", "Usluga")
                        .WithMany("RezervacijaUsluge")
                        .HasForeignKey("UslugaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rezervacija");

                    b.Navigation("Usluga");
                });

            modelBuilder.Entity("RentIO.Models.Apartman", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("RentIO.Models.Gost", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("RentIO.Models.Rezervacija", b =>
                {
                    b.Navigation("RezervacijaUsluge");
                });

            modelBuilder.Entity("RentIO.Models.Usluga", b =>
                {
                    b.Navigation("RezervacijaUsluge");
                });
#pragma warning restore 612, 618
        }
    }
}
